name: rtd-management-applied-econ

channels:
- conda
- conda-forge

dependencies:
- python=3.7
- jupyterlab
- jupyter
- pip
- pygraphviz
- sphinx>=1.4
- nbsphinx
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- ipython
- ipykernel
- pip:
    - sphinx_rtd_theme
    - cairosvg
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
    - parso<0.9.0
    - sphinxcontrib-bibtex<2.0
    - nbsphinx
